#include "lua_shared exports.h"
#include <windows.h>
#include <stdio.h>
#include <libloaderapi.h>

#define _GETADR(name)															\
	name = (unsigned int)GetProcAddress(GetModuleHandleA("lua_shared"), #name);	\
	if(!name)																	\
		printf("\n\nfailed getting %s!!!!\n\n",#name);							\

void exports::lua_shared::FillExports() {
	_GETADR(luaL_addlstring);
	_GETADR(luaL_addstring);
	_GETADR(luaL_addvalue);
	_GETADR(luaL_argerror);
	_GETADR(luaL_buffinit);
	_GETADR(luaL_callmeta);
	_GETADR(luaL_checkany);
	_GETADR(luaL_checkinteger);
	_GETADR(luaL_checklstring);
	_GETADR(luaL_checknumber);
	_GETADR(luaL_checkoption);
	_GETADR(luaL_checkstack);
	_GETADR(luaL_checktype);
	_GETADR(luaL_checkudata);
	_GETADR(luaL_error);
	_GETADR(luaL_execresult);
	_GETADR(luaL_fileresult);
	_GETADR(luaL_findtable);
	_GETADR(luaL_getmetafield);
	_GETADR(luaL_gsub);
	_GETADR(luaL_loadbuffer);
	_GETADR(luaL_loadbufferx);
	_GETADR(luaL_loadfile);
	_GETADR(luaL_loadfilex);
	_GETADR(luaL_loadstring);
	_GETADR(luaL_newmetatable);
	_GETADR(luaL_newmetatable_type);
	_GETADR(luaL_newstate);
	_GETADR(luaL_openlib);
	_GETADR(luaL_openlibs);
	_GETADR(luaL_optinteger);
	_GETADR(luaL_optlstring);
	_GETADR(luaL_optnumber);
	_GETADR(luaL_prepbuffer);
	_GETADR(luaL_pushresult);
	_GETADR(luaL_ref);
	_GETADR(luaL_register);
	_GETADR(luaL_traceback);
	_GETADR(luaL_typerror);
	_GETADR(luaL_unref);
	_GETADR(luaL_where);
	_GETADR(lua_atpanic);
	_GETADR(lua_call);
	_GETADR(lua_checkstack);
	_GETADR(lua_close);
	_GETADR(lua_concat);
	_GETADR(lua_cpcall);
	_GETADR(lua_createtable);
	_GETADR(lua_dump);
	_GETADR(lua_equal);
	_GETADR(lua_error);
	_GETADR(lua_gc);
	_GETADR(lua_getallocf);
	_GETADR(lua_getfenv);
	_GETADR(lua_getfield);
	_GETADR(lua_gethook);
	_GETADR(lua_gethookcount);
	_GETADR(lua_gethookmask);
	_GETADR(lua_getinfo);
	_GETADR(lua_getlocal);
	_GETADR(lua_getmetatable);
	_GETADR(lua_getstack);
	_GETADR(lua_gettable);
	_GETADR(lua_gettop);
	_GETADR(lua_getupvalue);
	_GETADR(lua_insert);
	_GETADR(lua_iscfunction);
	_GETADR(lua_isnumber);
	_GETADR(lua_isstring);
	_GETADR(lua_isuserdata);
	_GETADR(lua_lessthan);
	_GETADR(lua_load);
	_GETADR(lua_loadx);
	_GETADR(lua_newstate);
	_GETADR(lua_newthread);
	_GETADR(lua_newuserdata);
	_GETADR(lua_next);
	_GETADR(lua_objlen);
	_GETADR(lua_pcall);
	_GETADR(lua_pushboolean);
	_GETADR(lua_pushcclosure);
	_GETADR(lua_pushfstring);
	_GETADR(lua_pushinteger);
	_GETADR(lua_pushlightuserdata);
	_GETADR(lua_pushlstring);
	_GETADR(lua_pushnil);
	_GETADR(lua_pushnumber);
	_GETADR(lua_pushstring);
	_GETADR(lua_pushthread);
	_GETADR(lua_pushvalue);
	_GETADR(lua_pushvfstring);
	_GETADR(lua_rawequal);
	_GETADR(lua_rawget);
	_GETADR(lua_rawgeti);
	_GETADR(lua_rawset);
	_GETADR(lua_rawseti);
	_GETADR(lua_remove);
	_GETADR(lua_replace);
	_GETADR(lua_resume_real);
	_GETADR(lua_setallocf);
	_GETADR(lua_setfenv);
	_GETADR(lua_setfield);
	_GETADR(lua_sethook);
	_GETADR(lua_setlocal);
	_GETADR(lua_setmetatable);
	_GETADR(lua_settable);
	_GETADR(lua_settop);
	_GETADR(lua_setupvalue);
	_GETADR(lua_status);
	_GETADR(lua_toboolean);
	_GETADR(lua_tocfunction);
	_GETADR(lua_tointeger);
	_GETADR(lua_tolstring);
	_GETADR(lua_tonumber);
	_GETADR(lua_topointer);
	_GETADR(lua_tothread);
	_GETADR(lua_touserdata);
	_GETADR(lua_type);
	_GETADR(lua_typename);
	_GETADR(lua_upvalueid);
	_GETADR(lua_upvaluejoin);
	_GETADR(lua_xmove);
	_GETADR(lua_yield);
	_GETADR(luaopen_base);
	_GETADR(luaopen_bit);
	_GETADR(luaopen_debug);
	_GETADR(luaopen_jit);
	_GETADR(luaopen_math);
	_GETADR(luaopen_os);
	_GETADR(luaopen_package);
	_GETADR(luaopen_string);
	_GETADR(luaopen_table);
}

namespace exports
{
	namespace lua_shared
	{
		// Function addresses
		unsigned int	luaL_addlstring = 0;
		unsigned int	luaL_addstring = 0;
		unsigned int	luaL_addvalue = 0;
		unsigned int	luaL_argerror = 0;
		unsigned int	luaL_buffinit = 0;
		unsigned int	luaL_callmeta = 0;
		unsigned int	luaL_checkany = 0;
		unsigned int	luaL_checkinteger = 0;
		unsigned int	luaL_checklstring = 0;
		unsigned int	luaL_checknumber = 0;
		unsigned int	luaL_checkoption = 0;
		unsigned int	luaL_checkstack = 0;
		unsigned int	luaL_checktype = 0;
		unsigned int	luaL_checkudata = 0;
		unsigned int	luaL_error = 0;
		unsigned int	luaL_execresult = 0;
		unsigned int	luaL_fileresult = 0;
		unsigned int	luaL_findtable = 0;
		unsigned int	luaL_getmetafield = 0;
		unsigned int	luaL_gsub = 0;
		unsigned int	luaL_loadbuffer = 0;
		unsigned int	luaL_loadbufferx = 0;
		unsigned int	luaL_loadfile = 0;
		unsigned int	luaL_loadfilex = 0;
		unsigned int	luaL_loadstring = 0;
		unsigned int	luaL_newmetatable = 0;
		unsigned int	luaL_newmetatable_type = 0;
		unsigned int	luaL_newstate = 0;
		unsigned int	luaL_openlib = 0;
		unsigned int	luaL_openlibs = 0;
		unsigned int	luaL_optinteger = 0;
		unsigned int	luaL_optlstring = 0;
		unsigned int	luaL_optnumber = 0;
		unsigned int	luaL_prepbuffer = 0;
		unsigned int	luaL_pushresult = 0;
		unsigned int	luaL_ref = 0;
		unsigned int	luaL_register = 0;
		unsigned int	luaL_traceback = 0;
		unsigned int	luaL_typerror = 0;
		unsigned int	luaL_unref = 0;
		unsigned int	luaL_where = 0;
		unsigned int	lua_atpanic = 0;
		unsigned int	lua_call = 0;
		unsigned int	lua_checkstack = 0;
		unsigned int	lua_close = 0;
		unsigned int	lua_concat = 0;
		unsigned int	lua_cpcall = 0;
		unsigned int	lua_createtable = 0;
		unsigned int	lua_dump = 0;
		unsigned int	lua_equal = 0;
		unsigned int	lua_error = 0;
		unsigned int	lua_gc = 0;
		unsigned int	lua_getallocf = 0;
		unsigned int	lua_getfenv = 0;
		unsigned int	lua_getfield = 0;
		unsigned int	lua_gethook = 0;
		unsigned int	lua_gethookcount = 0;
		unsigned int	lua_gethookmask = 0;
		unsigned int	lua_getinfo = 0;
		unsigned int	lua_getlocal = 0;
		unsigned int	lua_getmetatable = 0;
		unsigned int	lua_getstack = 0;
		unsigned int	lua_gettable = 0;
		unsigned int	lua_gettop = 0;
		unsigned int	lua_getupvalue = 0;
		unsigned int	lua_insert = 0;
		unsigned int	lua_iscfunction = 0;
		unsigned int	lua_isnumber = 0;
		unsigned int	lua_isstring = 0;
		unsigned int	lua_isuserdata = 0;
		unsigned int	lua_lessthan = 0;
		unsigned int	lua_load = 0;
		unsigned int	lua_loadx = 0;
		unsigned int	lua_newstate = 0;
		unsigned int	lua_newthread = 0;
		unsigned int	lua_newuserdata = 0;
		unsigned int	lua_next = 0;
		unsigned int	lua_objlen = 0;
		unsigned int	lua_pcall = 0;
		unsigned int	lua_pushboolean = 0;
		unsigned int	lua_pushcclosure = 0;
		unsigned int	lua_pushfstring = 0;
		unsigned int	lua_pushinteger = 0;
		unsigned int	lua_pushlightuserdata = 0;
		unsigned int	lua_pushlstring = 0;
		unsigned int	lua_pushnil = 0;
		unsigned int	lua_pushnumber = 0;
		unsigned int	lua_pushstring = 0;
		unsigned int	lua_pushthread = 0;
		unsigned int	lua_pushvalue = 0;
		unsigned int	lua_pushvfstring = 0;
		unsigned int	lua_rawequal = 0;
		unsigned int	lua_rawget = 0;
		unsigned int	lua_rawgeti = 0;
		unsigned int	lua_rawset = 0;
		unsigned int	lua_rawseti = 0;
		unsigned int	lua_remove = 0;
		unsigned int	lua_replace = 0;
		unsigned int	lua_resume_real = 0;
		unsigned int	lua_setallocf = 0;
		unsigned int	lua_setfenv = 0;
		unsigned int	lua_setfield = 0;
		unsigned int	lua_sethook = 0;
		unsigned int	lua_setlocal = 0;
		unsigned int	lua_setmetatable = 0;
		unsigned int	lua_settable = 0;
		unsigned int	lua_settop = 0;
		unsigned int	lua_setupvalue = 0;
		unsigned int	lua_status = 0;
		unsigned int	lua_toboolean = 0;
		unsigned int	lua_tocfunction = 0;
		unsigned int	lua_tointeger = 0;
		unsigned int	lua_tolstring = 0;
		unsigned int	lua_tonumber = 0;
		unsigned int	lua_topointer = 0;
		unsigned int	lua_tothread = 0;
		unsigned int	lua_touserdata = 0;
		unsigned int	lua_type = 0;
		unsigned int	lua_typename = 0;
		unsigned int	lua_upvalueid = 0;
		unsigned int	lua_upvaluejoin = 0;
		unsigned int	lua_xmove = 0;
		unsigned int	lua_yield = 0;
		unsigned int	luaopen_base = 0;
		unsigned int	luaopen_bit = 0;
		unsigned int	luaopen_debug = 0;
		unsigned int	luaopen_jit = 0;
		unsigned int	luaopen_math = 0;
		unsigned int	luaopen_os = 0;
		unsigned int	luaopen_package = 0;
		unsigned int	luaopen_string = 0;
		unsigned int	luaopen_table = 0;
	};
};